apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: product-app
    tier: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
  MYSQL_USER: cHJvZHVjdHVzZXI=
  MYSQL_PASSWORD: cHJvZHVjdHBhc3M=
